export const Images =  {
    LOGO_LIGHT: require("./logo_light.png"),
    DEFAULT_USER_PICTURE: require("./default_user_picture.png"),
    UPLOAD_ARROW: require("./upload_arrow.png"),
    CHECKMARK: require("./checkmark.png"),
    SHPE_LOGO: require("./shpe_logo.png"),
    CAROUSEL_1: require("./carousel_1.jpg"),
    CAROUSEL_2: require("./carousel_2.jpg"),
    CAROUSEL_3: require("./carousel_3.jpg"),
    EBOARD: require("./e-board20.jpg"),
    LDMAIN: require("./LDMain.jpg"),
    MEMBERSHPE: require("./memberSHPEPic2.jpg"),
    TAMU_WHITE: require("./TAM-Logo-white.png"),
    TAMU_MAROON: require("./TAM-Logo-maroon.png"),
    GENEVA: require("./geneva.png"),
    INSTAGRAM: require("./Instagram-Logo.png"),
    FLICKER: require("./flicker.png"),
    SHPE_LOGO_VERT:require("./SHPE_Logo_Vert.png"),
    COMMITTEE_1: require("./committee_1.png"),
    COMMITTEE_2: require("./committee_2.png"),
    COMMITTEE_3: require("./committee_3.png"),
    COMMITTEE_4: require("./committee_4.png"),
    COMMITTEE: require("./committee.png"),
    EVENT: require("./event.png"),
};
